import os
from typing import Dict, Any
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


class MCPDocumentGenerator:
    def __init__(self):
        pass

    def generate_document(self, unified_payload: Dict[str, Any], output_path: str) -> str:
        doc = Document()
        metadata = unified_payload.get("document_metadata", {})
        doc.core_properties.title = metadata.get("title", "SDLC Document")
        doc.core_properties.author = "SDLC MCP Pipeline"
        doc.core_properties.comments = f"Generated by MCP Pipeline on {datetime.now().strftime('%Y-%m-%d %H:%M')}"

        self._add_cover_page(doc, metadata)
        doc.add_page_break()
        self._add_toc_placeholder(doc)
        doc.add_page_break()
        self._add_overview(doc, unified_payload)
        doc.add_page_break()
        self._add_requirements_section(doc, unified_payload.get("requirements", []))
        doc.add_page_break()
        self._add_business_logic_section(doc, unified_payload)
        doc.add_page_break()
        self._add_change_requests_section(doc, unified_payload.get("change_requests", []))
        doc.add_page_break()
        self._add_data_tables_section(doc, unified_payload.get("table_map", []))
        doc.add_page_break()
        self._add_validation_report(doc, unified_payload.get("validation_summary", {}))

        doc.save(output_path)
        print(f"[Doc Maker] ✓ Document generated: {output_path}")
        return output_path
    
    def _add_cover_page(self, doc: Document, metadata: Dict[str, Any]):
        title = doc.add_heading(metadata.get("title", "SDLC Document"), level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()
        doc.add_paragraph()

        info_table = doc.add_table(rows=5, cols=2)
        info_table.style = 'Light Grid Accent 1'
        info_data = [
            ("Version:", metadata.get("version", "1.0")),
            ("Date:", metadata.get("date", datetime.now().strftime("%Y-%m-%d"))),
            ("Author:", metadata.get("author", "SDLC MCP Pipeline")),
            ("Project Code:", metadata.get("project_code", "N/A")),
            ("Generated:", datetime.now().strftime("%Y-%m-%d %H:%M"))
        ]
        for i, (label, value) in enumerate(info_data):
            info_table.rows[i].cells[0].text = label
            info_table.rows[i].cells[1].text = str(value)
            info_table.rows[i].cells[0].paragraphs[0].runs[0].bold = True
    
    def _add_toc_placeholder(self, doc: Document):
        doc.add_heading("Table of Contents", level=1)
        para = doc.add_paragraph()
        para.add_run("Table of Contents will be auto-generated when opened in Microsoft Word.\n")
        para.add_run("Right-click and select 'Update Field' to refresh.").italic = True

    def _add_overview(self, doc: Document, unified_payload: Dict[str, Any]):
        doc.add_heading("Document Overview", level=1)
        metadata = unified_payload.get("document_metadata", {})
        doc.add_paragraph(
            f"This document was generated by the MCP Multi-Agent Pipeline from the source file: "
            f"{metadata.get('filename', 'Unknown')}. It contains structured requirements, business logic, "
            f"data tables, and validation results."
        )
        doc.add_heading("Summary Statistics", level=2)
        stats_table = doc.add_table(rows=5, cols=2)
        stats_table.style = 'Light List Accent 1'
        stats_data = [
            ("Total Requirements:", len(unified_payload.get("requirements", []))),
            ("Total Tables:", len(unified_payload.get("table_map", []))),
            ("Business Rules:", len(unified_payload.get("business_rules", []))),
            ("Process Flows:", len(unified_payload.get("flows", []))),
            ("Change Requests:", len(unified_payload.get("change_requests", [])))
        ]
        for i, (label, value) in enumerate(stats_data):
            stats_table.rows[i].cells[0].text = label
            stats_table.rows[i].cells[1].text = str(value)
    
    def _add_requirements_section(self, doc: Document, requirements: list):
        doc.add_heading("Requirements", level=1)
        if not requirements:
            doc.add_paragraph("No requirements extracted from the document.")
            return
        doc.add_paragraph(
            f"This section contains {len(requirements)} requirements extracted from the source document, "
            f"categorized by type and priority."
        )
        table = doc.add_table(rows=1, cols=6)
        table.style = 'Light Grid Accent 1'
        headers = ["Req ID", "Type", "Description", "Priority", "Source Section", "Linked CR"]
        header_cells = table.rows[0].cells
        for i, header in enumerate(headers):
            header_cells[i].text = header
            self._format_table_header_cell(header_cells[i])
        for req in requirements:
            row_cells = table.add_row().cells
            row_cells[0].text = req.get("id", "")
            row_cells[1].text = req.get("type", "")
            row_cells[2].text = req.get("description", "")
            row_cells[3].text = req.get("priority", "")
            row_cells[4].text = req.get("source_section", "")
            row_cells[5].text = ", ".join(req.get("linked_cr", []))
        self._apply_alternating_row_colors(table)
    
    def _add_business_logic_section(self, doc: Document, unified_payload: Dict[str, Any]):
        doc.add_heading("Business Logic & Rules", level=1)
        rules = unified_payload.get("business_rules", [])
        if rules:
            doc.add_heading("Business Rules", level=2)
            table = doc.add_table(rows=1, cols=5)
            table.style = 'Light Grid Accent 1'
            headers = ["Rule ID", "Condition", "Action", "Source Section", "Priority"]
            header_cells = table.rows[0].cells
            for i, header in enumerate(headers):
                header_cells[i].text = header
                self._format_table_header_cell(header_cells[i])
            for rule in rules:
                row_cells = table.add_row().cells
                row_cells[0].text = rule.get("id", "")
                row_cells[1].text = rule.get("condition", "")
                row_cells[2].text = rule.get("action", "")
                row_cells[3].text = rule.get("source_section", "")
                row_cells[4].text = rule.get("priority", "")
            self._apply_alternating_row_colors(table)
        else:
            doc.add_paragraph("No business rules extracted.")

        flows = unified_payload.get("flows", [])
        if flows:
            doc.add_heading("Process Flows", level=2)
            for flow in flows:
                doc.add_heading(f"{flow.get('id', '')}: {flow.get('name', '')}", level=3)
                doc.add_paragraph(f"Source: {flow.get('source_section', '')}")
                for i, step in enumerate(flow.get("steps", []), 1):
                    doc.add_paragraph(f"{i}. {step}", style='List Number')
        else:
            doc.add_paragraph("No process flows extracted.")
    
    def _add_change_requests_section(self, doc: Document, change_requests: list):
        doc.add_heading("Change Requests", level=1)
        if not change_requests:
            doc.add_paragraph("No change requests identified in the document.")
            return
        table = doc.add_table(rows=1, cols=5)
        table.style = 'Light Grid Accent 1'
        headers = ["CR ID", "Description", "Delta Type", "Impacted Sections", "Impacted Tables"]
        header_cells = table.rows[0].cells
        for i, header in enumerate(headers):
            header_cells[i].text = header
            self._format_table_header_cell(header_cells[i])
        for cr in change_requests:
            row_cells = table.add_row().cells
            row_cells[0].text = cr.get("cr_id", "")
            row_cells[1].text = cr.get("description", "")
            row_cells[2].text = cr.get("delta_type", "")
            row_cells[3].text = ", ".join(cr.get("impacted_sections", []))
            row_cells[4].text = ", ".join(cr.get("impacted_tables", []))
        self._apply_alternating_row_colors(table)
    
    def _add_data_tables_section(self, doc: Document, table_map: list):
        doc.add_heading("Data Tables", level=1)
        if not table_map:
            doc.add_paragraph("No tables extracted from the document.")
            return
        for i, table_data in enumerate(table_map, 1):
            caption = doc.add_paragraph()
            caption_run = caption.add_run(f"Table {i}: {table_data.get('caption', 'Untitled Table')}")
            caption_run.bold = True
            caption_run.font.size = Pt(11)
            doc.add_paragraph(f"Location: {table_data.get('location_section', 'Unknown')}")
            doc.add_paragraph(f"Row Count: {table_data.get('row_count', 0)}")
            headers = table_data.get("headers", [])
            rows = table_data.get("rows", [])
            if headers and rows:
                table = doc.add_table(rows=1, cols=len(headers))
                table.style = 'Light Grid Accent 1'
                header_cells = table.rows[0].cells
                for j, header in enumerate(headers):
                    header_cells[j].text = str(header)
                    self._format_table_header_cell(header_cells[j])
                for row_data in rows:
                    row_cells = table.add_row().cells
                    for j, cell_value in enumerate(row_data):
                        if j < len(row_cells):
                            row_cells[j].text = str(cell_value)
                self._apply_alternating_row_colors(table)
            anomalies = table_data.get("anomalies", [])
            if anomalies:
                doc.add_paragraph("Anomalies detected:", style='Intense Quote')
                for anomaly in anomalies:
                    doc.add_paragraph(
                        f"• Row {anomaly.get('row', '?')}, Col {anomaly.get('col', '?')}: {anomaly.get('issue', '')}",
                        style='List Bullet'
                    )
            doc.add_paragraph()
    
    def _add_validation_report(self, doc: Document, validation_summary: Dict[str, Any]):
        doc.add_heading("Validation Report", level=1)
        passed = validation_summary.get("passed", False)
        status_para = doc.add_paragraph()
        status_run = status_para.add_run(f"Status: {'✓ PASSED' if passed else '✗ FAILED'}")
        status_run.bold = True
        status_run.font.size = Pt(14)
        status_run.font.color.rgb = RGBColor(0, 128, 0) if passed else RGBColor(255, 0, 0)
        doc.add_paragraph(f"Validation Run: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        warnings = validation_summary.get("warnings", [])
        if warnings:
            doc.add_heading("Warnings", level=2)
            for warning in warnings:
                doc.add_paragraph(
                    f"⚠ [{warning.get('type', 'unknown')}] {warning.get('location', '')}: {warning.get('detail', '')}",
                    style='List Bullet'
                )
        else:
            doc.add_paragraph("No warnings detected.")
        errors = validation_summary.get("errors", [])
        if errors:
            doc.add_heading("Errors", level=2)
            for error in errors:
                doc.add_paragraph(
                    f"✗ [{error.get('type', 'unknown')}] {error.get('location', '')}: {error.get('detail', '')}",
                    style='List Bullet'
                )
        else:
            doc.add_paragraph("No errors detected.")

    def _format_table_header_cell(self, cell):
        shading_elm = OxmlElement('w:shd')
        shading_elm.set(qn('w:fill'), '1F4E79')
        cell._element.get_or_add_tcPr().append(shading_elm)
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.font.color.rgb = RGBColor(255, 255, 255)
                run.font.bold = True
                run.font.size = Pt(10)

    def _apply_alternating_row_colors(self, table):
        for i, row in enumerate(table.rows[1:], 1):
            color = 'FFFFFF' if i % 2 == 1 else 'F2F2F2'
            for cell in row.cells:
                shading_elm = OxmlElement('w:shd')
                shading_elm.set(qn('w:fill'), color)
                cell._element.get_or_add_tcPr().append(shading_elm)


class MCPGiverAgent:
    def deliver_document(self, document_path: str, delivery_mode: str = "download", **kwargs) -> Dict[str, Any]:
        if not os.path.exists(document_path):
            return {
                "status": "failed",
                "timestamp": datetime.now().isoformat(),
                "mode": delivery_mode,
                "error": "Document file not found"
            }

        confirmation = {
            "status": "delivered",
            "timestamp": datetime.now().isoformat(),
            "mode": delivery_mode,
            "file": os.path.basename(document_path),
            "file_path": document_path,
            "file_size": os.path.getsize(document_path),
            "retries": 0
        }

        if delivery_mode == "download":
            print(f"[Giver Agent] ✓ Document ready for download: {document_path}")
        elif delivery_mode == "api_response":
            confirmation["ready_for_response"] = True
        elif delivery_mode == "webhook":
            confirmation["webhook_url"] = kwargs.get("webhook_url")
        elif delivery_mode == "email":
            confirmation["recipient"] = kwargs.get("recipient_email")

        return confirmation


# Singleton instances
mcp_doc_generator = MCPDocumentGenerator()
mcp_giver_agent = MCPGiverAgent()
